### ISSUE TITLE
SRO cannot deploy the simple-kmod example special resource

### ISSUE THREAD

**Issue by hershpa** [openshift/special-resource-operator#228] opened 2022-06-15 23:24 UTC
**Summary**
We install the SRO from **CLI** using the master branch of this repo. We see the following error in SRO controller manager logs: "Could not reconcile chart for SpecialResource","reconciler group":"sro.openshift.io","reconciler kind":"SpecialResource","name":"simple-kmod","namespace":"","error":"failed to get /simple-kmod runtime info: failed to get upgrade info: failed to extract dtk versions: DTK kernel not found running in the cluster. kernelFullVersion: 4.18.0-305.45.1.el8_4.x86_64. rtKernelFullVersion: 4.18.0-305.45.1.rt7.117.el8_4.x86_64"}"  We see the SRO is not deploying the simple-kmod example special resource due to above error. 

**Steps to reproduce:**
Env: OpenShift 4.10.16 Cluster
$ git clone https://github.com/openshift/special-resource-operator
$ cd special-resource-operator
$ TAG=master make deploy. We are specifically using **commit** 4e45f0dc74ce4c6383626001716eb6e64251df8e

The following will create "simple-kmod-0.0.1" ConfigMap in "default" namespace
$ ./scripts/make-cm-recipe ./charts/example/simple-kmod-0.0.1 simple-kmod-0.0.1 default

Also, there is a slight issue in Readme: 
Readme says "# name and namespace can be specified
$ ./scripts/make-cm-recipe ./charts/example/simple-kmod-0.0.1 namespace configmap-name"

However, configmap-name needs to be specified first followed by namespace. Like this:
"$ ./scripts/make-cm-recipe ./charts/example/simple-kmod-0.0.1 configmap-name namespace"

Finally: 
oc apply -f charts/example/simple-kmod-0.0.1/simple-kmod.yaml

The command runs successfully but no special resource created.

**Findings:**
We see the SRO is not deploying the simple-kmod example special resource. As a result, we looked at relevant logs and find below.
We see the following error in SRO controller manager logs: "Could not reconcile chart for SpecialResource","reconciler group":"sro.openshift.io","reconciler kind":"SpecialResource","name":"simple-kmod","namespace":"","error":"failed to get /simple-kmod runtime info: failed to get upgrade info: failed to extract dtk versions: DTK kernel not found running in the cluster. kernelFullVersion: 4.18.0-305.45.1.el8_4.x86_64. rtKernelFullVersion: 4.18.0-305.45.1.rt7.117.el8_4.x86_64"}"

**For reference, the charts/example/simple-kmod-0.0.1/simple-kmod.yaml file below:**
apiVersion: sro.openshift.io/v1beta1
kind: SpecialResource
metadata:
  name: simple-kmod
spec:
  namespace: simple-kmod
  chart:
    name: simple-kmod
    version: 0.0.1
    repository:
      name: simple-kmod
      url: cm://default/simple-kmod-0.0.1
  set:
    kind: Values
    apiVersion: sro.openshift.io/v1beta1
    kmodNames: ["simple-kmod", "simple-procfs-kmod"]
    buildArgs:
    - name: "KMODVER"
      value: "SRO"
  driverContainer:
    source:
      git:
        ref: "master"
        uri: "https://github.com/openshift-psap/simple-kmod.git"

**Comment by hershpa** [comment] 2022-06-16 16:07
We are using OCP 4.10.16.

**Comment by bthurber** [comment] 2022-06-16 16:12
> 

Thanks.  Another possibility would be to use the release-4.10 branch vs. main and see if the issue persists.

**Comment by hershpa** [comment] 2022-06-16 16:17
Got it, so release-4.10 branch is specifically for OCP 4.10.z releases?

**Comment by bthurber** [comment] 2022-06-22 02:18
Hi @hershpa did you have success with the 4.10 branch?

**Comment by Walnux** [comment] 2022-06-22 06:51
@hershpa retry the master branch on OCP-4.10.17 still has above issue. the error log is:
{"level":"info","ts":1655880464.4495997,"logger":"controller.specialresource","msg":"WARNING: RECONCILE REQUEUE: Could not reconcile chart for SpecialResource","reconciler group":"sro.openshift.io","reconciler kind":"SpecialResource","name":"simple-kmod","namespace":"","error":"failed to get /simple-kmod runtime info: failed to get upgrade info: failed to extract dtk versions: failed to extact dtk data from image url quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:0661d0560654e7e2d1761e883ffdd6c482c8c8f37e60608bb59c44fa81a3f0bb: failed to get layers digests of the image quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:0661d0560654e7e2d1761e883ffdd6c482c8c8f37e60608bb59c44fa81a3f0bb: failed to get manifest stream from image quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:0661d0560654e7e2d1761e883ffdd6c482c8c8f37e60608bb59c44fa81a3f0bb: failed to get crane manifest from image quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:0661d0560654e7e2d1761e883ffdd6c482c8c8f37e60608bb59c44fa81a3f0b...

**Comment by ybettan** [comment] 2022-06-26 10:08
Hello @hershpa @Walnux.

Thanks for that issue.

1. It doesn't matter what branch you are using. There is no `TAG` in the makefile, therefore, when running `make deploy` without specifying `IMG=...` you are running with the default image which is `quay.io/openshift/origin-special-resource-rhel8-operator:latest`

2. You both pointed up different issues. I can't reproduce @hershpa 's issue cause I don't know what image was used. Regarding @Walnux issue, you cut the most important part of the error :) If we got the same error then the "deepest" error is `loading registries configuration "/mnt/host/registries.conf": open /mnt/host/registries.conf: no such file or directory' which is most probably caused by the latest support for disconnected envs - see [PR](https://github.com/openshift/special-resource-operator/pull/226)

I indeed see that the volume wasn't mount to the container for some reason:
```
root special-resource-operator (downstream) $ oc get pod/special-resource-controller-manager-69df7698d8-rgsjz -n openshift-special-resource-operator -o json | jq '.spec.containers[1].volumeMounts'
[
  {
    "mountPath": "/home/nonroot/.cache",
    "name": "cache-volume"
  },
  {
    "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
    "name": "kube-api-access-q99mc",
    "readOnly": true
  }
]
```
and not even mounted to the pod:
```
root special-resource-operator (downstream) $ oc get pod/special-resource-controller-manager-69df7698d8-rgsjz -n openshift-special-resource-operator -o json | jq '.spec.volumes[].name'
"special-resource-operator-tls"
"cache-volume"
"kube-api-access-q99mc"
```

FYI @qbarrand.

Let's start with running a matching deployment-config <--> image. The way to do it is to make sure you are deploying with `make deploy IMG=<the image that match the config yaml.

For future official releases you can deploy from operatorHub (make sure to deploy NFD first for simple-kmod) by applying:
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-special-resource-operator
  namespace: openshift-operators
spec:
  channel: stable
  name: openshift-special-resource-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
```
in the cluster.

If you have futures issue with a clean deployment please supply the exact `IMG` used to deploy and what commit sha your deployed from.

**Comment by bthurber** [comment] 2022-07-12 20:20
@hershpa is you issue resolved?  OK to close this?

**Closed** 2022-07-12 20:23 UTC
